### ISSUE TITLE
NPM install error using default responses to prompts

### ISSUE THREAD

**Issue by tomwayson** [odoe/generator-arcgis-js-app#1]
When using the default values to the prompts, I get `npm ERR! Invalid name: "yo arcgis js app"` error during NPM install (see console output excerpt below).

``` bash
I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.


npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\tom6947\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.4.1

npm ERR! Invalid name: "yo arcgis js app"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\test\yo-arcgis-js-app\npm-debug.log
```

After updating the name in package.json to `yo-arcgis-js-app` <del>and running</del> I can run `npm install` successfully.

**Comment by odoe** [comment]
Weird, that is the name in the `package.json`. Can you test one more time and close if it works.

**Comment by tomwayson** [comment]
I'm s still getting this error w/

generator-arcgis-js-app v0.0.9
node v0.12.7
Windows 7.???

Basically, I think "yo ags js app" is not a valid package name.

Sorry, I think my first comment wasn't clear, I've updated it to reflect that I was able to successfully run `npm install` _manually_ after updating the name in package.json to updating the name in package.json to 'yo-arcgis-js-app'.

**Comment by odoe** [comment]
What's your Yeoman version? I tried with 1.4.8 worked on Windows and Linux. 1.4.6 and worked on my Mac, then upgraded to 1.4.8 and still worked.

It's weird that you had to rename it, that goes against the yeoman conventions in the docs. It should recognize `generator-name`

**Comment by tomwayson** [comment]
yo@1.4.6

**Comment by tomwayson** [comment]
It looks like you're [binding this in the template to `appname`](https://github.com/odoe/generator-arcgis-js-app/blob/c290d84abe6a2539ee5ae68155a97c164ce94a01/generators/app/templates/src/app/_package.json#L2) and it looks like that [is defaulting to the name of the folder](https://github.com/odoe/generator-arcgis-js-app/blob/35132b9dbd6266996d312fb2dfe90c780fc62185/generators/app/index.js#L20).

Previously, when I had the errors, I was running in a folder w/ dashes in the name (C:\code\test\yo-ags-js-app), then I tried in a new folder w/ no dashes (C:\code\test\yoagsjsapp) and everything worked (including #4).

Also, something that's jumps out at me, I would expect [this line](https://github.com/odoe/generator-arcgis-js-app/blob/35132b9dbd6266996d312fb2dfe90c780fc62185/generators/app/index.js#L49) not to work, and that it should be:

``` js
        appname: this.props.appname,
```

Obviously there's something I missed that makes that work.

**Comment by odoe** [comment]
_Magic!_ Yeah, I don't know why that works, looks like I typoed that line. I'll update this tonight on my local machine and see if it fixes your issue. I think I'll also `camelize(x).toLowerCase()` the appname to avoid issues with app with dashes.

In the meantime, for anyone looking, don't use `-` in app names.
