### ISSUE TITLE
Add option to use Sass instead of Stylus

### ISSUE THREAD

**Issue by tomwayson** [odoe/generator-arcgis-js-app#10]
App generator should prompt user if they want to use Sass or Stylus.

From our discussions, sounds like you're on board w/ this, just adding issue to document and confirm that you're also OK w/ defaulting to Sass (which is what I think most people use). I can default to Stylus if you prefer.

**Comment by odoe** [comment]
Let's make Sass the default and I'm assuming using `node-sass` for the build. Let's have a note in the README for it, maybe with a link to this [compatibility chart](http://sass-compatibility.github.io/) between the libass and Ruby version.

**Comment by tomwayson** [comment]
Yep, w/ libsass and good idea about the compatibility chart. In progress...

**Comment by odoe** [comment]
added in 1.0,0
