### ISSUE TITLE
issues re: moment dependency

### ISSUE THREAD

**Issue by jccartwright** [odoe/generator-arcgis-js-app#14]
It appears there is some discrepancy between recent commits and what's available in yeoman. I found that I had to:
1) npm install moment
2) edit the tests/intern.js to reproduce commit 5a20d09

**Comment by odoe** [comment]
That's weird, did you try an `npm cache clean`?

I just ran it this morning and that commit was there.

**Comment by tomwayson** [comment]
@jccartwright do you have v0.2.3? That's one includes the moment fix and works for me.

**Comment by odoe** [comment]
No further comments, seems to be working fine.
