### ISSUE TITLE
Bower as a dependency?

### ISSUE THREAD

**Issue by tannerjt** [odoe/generator-arcgis-js-app#20]
Since the generator relies on bower for client dependencies, should it be required in the root package.json as a dependency of the generator?  On my machine, I didn't have have bower already installed as a global package.  Running the generator failed with 'bower' is not recognized as an internal or external command.

I would propose either adding bower as a dependency of the generator, or adding to the documentation the need for `npm install -g bower`.  

Does that sound right, or should it be assumed users already have bower installed globally?

**Comment by odoe** [comment]
That makes sense. I can add that snippet to the readme and I'll also test if having local Bower will work as expected too.

**Comment by tannerjt** [comment]
Thanks @odoe , by the way, this is a great utility!  Being able to use ES2015 with the Esri JS API is super helpful.
