### ISSUE TITLE
Locale missing in release-build

### ISSUE THREAD

**Issue by SpatialJ** [odoe/generator-arcgis-js-app#21]
Hi Rene, i'm trying your yeoman generator. great stuff!
I got a problem with locales though in the release build, it tries to load this resource file:
http://localhost/srl-test-client/nls/dojo_de.js
 
since there is no nls folder in release I figure the locale is baked into the release and the german files are missing.
How can include them into the build?
 
Thanks,
Johannes

**Comment by odoe** [comment]
You can do one of two things in the generated app.

1. Add the locale into the built layer [here](https://github.com/odoe/generator-arcgis-js-app/blob/master/generators/app/templates/profiles/4x/build.profile.js#L123)
2. Adjust the Gruntfile to remove the [copy portions of the release task](https://github.com/odoe/generator-arcgis-js-app/blob/master/generators/app/templates/Gruntfile.js#L356) so it doesn't copy files into a release folder. This way you just get all the files in a single `built` folder. You may need to adjust the processHTML bits so it's point to `dojo/dojo.js` and not `app.js`.

Thanks!

**Comment by SpatialJ** [comment]
I tried option (1) and it worked! Thank you :-)
