### ISSUE TITLE
Updated router structure

### ISSUE THREAD

**Issue by odoe** [odoe/generator-arcgis-js-app#5]
I'm toying around with the idea of updating the current `dojo/router` implementation. I've really grown to like the Ember [router.js](https://github.com/tildeio/router.js) way of routing. There's nothing in there that the `dojo/router` can't do, it just wraps some bare metal behavior away from the user.

I was thinking that in order to help devs rapidly get up and running with routing in their apps, we can do something similar.

Here's a gist with some ideas
https://gist.github.com/odoe/80a0600719b32e6571c5

My idea was to wrap the `dojo/router` in a new class (not extend it).

``` javascript
import dojoRouter from 'dojo/router';

class Router {

  constructor(handlers) {
    // pass an array that maps routes to handlers
    this.handlers = handlers;
  }

  map(routes) {
    let registered = routes.map(x => {
      let handle = this.handlers[x.name];
      return dojoRouter.register(x.path, handle);
    });
    dojoRouter.startup('/');
    return registered;
  }

}

export default Router;
```

Then each router would have it's own simple object that has a `setup` method where the route params can be passed and determine what updates to the page should be made.

``` javascript
import Application from '../templates/Application';

let node = document.getElementById('app-container');

let app;
let webmapid;

const Index = {
  setup(config) {
    // render page or add elements
    console.log('my index route', config);
    if (config.webmap && config.webmap.webmapid) {
      webmapid = config.webmap.webmapid;
    }

    if (webmapid) {
      app = new Application({ webmapid }, node);
    } else if (config.mapOptions){
      app = new Application({ mapOptions: config.mapOptions }, node);
    }
    return app;
  }
};

export default Index;
```

What's not shown here is a possible `model` method that `router.js` uses, where you call the model method, it returns the model data for the page (synchronous/asynchronous) and that data is used as the model for the route to pass to components. Unsure on this one so far, may be a better way to implement this in Dojo.

Right now I'm binding all this together in a `main.js`, but I'm thinking the base `Router` goes in a different folder and the below code goes into `router.js` at the root and `main.js` is used only to pull in and modify configuration data as needed. So the below code may get wrapped in a simple `startup` method that `main.js` can initialize.

``` javascript
import topic from 'dojo/topic';
import config from 'app/config';
import Router from './router';
import Index from './routes/index';

let handlers = {
  index() {
    console.log('app index');
    Index.setup(config);
  },

  webmap(e) {
    console.log('webmap');
    topic.publish('web-map-update', e.params);
  },

  foo(e) {
    console.log('call a foo route');
  }
};

let router = new Router(handlers);

router.map([{
  path: '/', name: 'index'
}, {
  path: '/foo', name: 'foo'
}, {
  path: '/webmap/:mapid', name: 'webmap'
}]);
```

Looking for feedback here from anyone interested in this generator. Could even possible make the whole route architecture optional during the initial app generation. We would also add a generator for the routes themselves and maybe even injecting the routes into the `router.js`.

cc @tomwayson

**Comment by odoe** [comment]
Looking at it, maybe `Router` shouldn't even be a class. This way it can get passed around wrap `dojo/router#go` or simply state that users should utilize `dojo/router#go` in their views.

**Comment by odoe** [comment]
After lots of app prototyping, I think I'll just remove the whole `Router` as part of the app structure. I think it just takes a level of complexity that is out of scope for the project. It doesn't stop someone from adding it themselves if they want.

I'll wait until a version 1.0 release, as I also want to add the TypeScript option alongside ES6, but that needs way more testing.

**Comment by tomwayson** [comment]
Yeah, sorry I didn't reply earlier. I think this is a _really_ cool idea, but TBH, we don't often use routes in the apps we build, and even when we do, it's not for map-focused apps, so preserving map state has not been a concern.

I agree that it's out of scope and will make the generator harder to maintain and enhance (i.e. add TS as an option, which I think will be more valuable in the long run).
