### ISSUE TITLE
unit tests fail on default app

### ISSUE THREAD

**Issue by jccartwright** [odoe/generator-arcgis-js-app#6]
It appears that a generated app w/o any modification fails the unit tests (http://localhost:8282/node_modules/intern/client.html?config=tests/intern) with errors like:

`TypeError: View is not a function
  at Test.registerSuite.View publishes a valid map [as test]  </tests/unit/components-map-mapview.js:30:17>
  at eval  </node_modules/intern//lib/Test.js:211:24>
  at eval  </node_modules/intern//node_modules/dojo/Promise.js:156:41>
  at runCallbacks  </node_modules/intern//node_modules/dojo/Promise.js:19:22>
  at eval  </node_modules/intern//node_modules/dojo/Promise.js:103:21>
  at run  </node_modules/intern//node_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  </node_modules/intern//node_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.eval  </node_modules/intern//node_modules/dojo/nextTick.js:52:27>`

Is it possible that there's a problem with the require?
`var View = require('app/components/map/MapView');`

**Comment by odoe** [comment]
This should be fixed in latest release. Because of ES6 modules, in the unit tests, this line needs to be `var View = require('app/components/map/MapView').default`. I also skip tests for modules not used by default in the app.

**Comment by jccartwright** [comment]
Thanks, that does seem to address the issue above.  However, I'm still finding a problem with the command-line runner, e.g. 

```
cougar:testme jcc$ ./node_modules/.bin/intern-client config=tests/intern
Error: ENOENT: no such file or directory, open '/Users/jcc/testme/node_modules/.bin/main.js'
at Error  <native>
at Object.fs.openSync  <fs.js:584:18>
at Object.fs.readFileSync  <fs.js:431:33>
at Function.nodeConfig.loaderPatch.getText  <node_modules/dojo/_base/configNode.js:80:15>
at injectModule  <node_modules/dojo/dojo.js:1539:12>
at forEach  <node_modules/dojo/dojo.js:93:6>
at <node_modules/dojo/dojo.js:758:5>
at guardCheckComplete  <node_modules/dojo/dojo.js:1277:5>
at injectDependencies  <node_modules/dojo/dojo.js:757:4>
at contextRequire  <node_modules/dojo/dojo.js:821:6>
```

Is that to be expected?

**Comment by odoe** [comment]
That doesn't look right. Maybe do another `npm install` to be safe. The command line runner will fail to run unit tests though, it will only work for functional tests.

**Comment by jccartwright** [comment]
thanks for the reply.  running "npm install" again didn't seem to make any difference.  I'm confused by your statement that the command-line runner only works for unit tests though.  Is that just in the app produced by the Yeoman generator?  I see that the command-line runner runs non-functional tests in the intern-tutorial.
